# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - chrome
        - electron

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  e2e-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Chrome
      if: ${{ github.event.inputs.choice == 'chrome' }} 
      uses: browser-actions/setup-chrome@v1
    
    - name: Installing Dependencies
      run: npm install
    
    - name: E2E Testing
      run: npx cypress run --spec 
      
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: relatorio-E2E
        path: ./cypress/reports

    - name: Report E2E Test - HTML Preview
      id: html_preview
      uses: pavi2410/html-preview-action@v4
      with:
          html_file: './cypress/reports/html/index.html'
          job_summary: true