# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - chrome
        - electron

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - name: Start Server
        run: echo "In this step, the server will run"

  smoke-e2e-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [start-server]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Chrome
      if: ${{ github.event.inputs.choice == 'chrome' }} 
      uses: browser-actions/setup-chrome@v1
    
    - name: Installing Dependencies
      run: npm install
    
    - name: run E2E Smoke test
      run: npx cypress run --env grepTags=smoke --browser=${{github.event.inputs.choice}}  
    
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: relatorio-E2E
        path: ./cypress/reports
  
  
  deploy:
      runs-on: ubuntu-latest
      needs: [smoke-e2e-test]
      steps:
        - name: Deploy
          run: echo "In this step, make the deploy"
  
  e2e-test:
        # The type of runner that the job will run on
     runs-on: ubuntu-latest
     needs: [deploy]
     steps:
      - uses: actions/checkout@v4
      
      - name: Install Chrome
        if: ${{ github.event.inputs.choice == 'chrome' }} 
        uses: browser-actions/setup-chrome@v1
      
      - name: Installing Dependencies
        run: npm install
      
      - name: run E2E Smoke test
        run: npx cypress run --browser=${{github.event.inputs.choice}}    
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-E2E
          path: ./cypress/reports


 